# Generated by Django 2.2.6 on 2019-11-02 20:41

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=main.models.user_directory_path)),
                ('location', models.CharField(max_length=30)),
                ('cost', models.IntegerField()),
                ('property_type', models.CharField(choices=[('Residential', 'Residential'), ('Business', 'Business')], max_length=15)),
            ],
        ),
    ]
