# Generated by Django 2.2.6 on 2019-11-03 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191103_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='location',
            new_name='place',
        ),
    ]
