# Generated by Django 2.2.6 on 2019-11-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_property_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(default='A building', max_length=700),
            preserve_default=False,
        ),
    ]
