# Generated by Django 2.2.6 on 2019-11-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_property_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.AddField(
            model_name='property',
            name='filename',
            field=models.SlugField(default='1', max_length=30),
            preserve_default=False,
        ),
    ]
